blank_issues_enabled: false
contact_links:
  - name: ‚ùì Support Question
    url: https://github.com/Lennolium/swiftGuard/discussions/new?category=questions-and-answers
    about: Get friendly support from the community on the forum.

  - name: ‚ú® Request a Feature
    url: https://github.com/Lennolium/swiftGuard/discussions/new?category=feature-requests
    about: Learn how to request a new feature.

  - name: ü§µ Get Professional Support & Customizations
    url: https://github.com/Lennolium
    about: Skip the line and get priority support directly from me.
