blank_issues_enabled: false
contact_links:
  - name: ‚ùì Support Question
    url: https://github.com/Lennolium/swiftGuard/discussions/new/choose
    about: Get friendly support from the community on the forum.

  - name: ‚ú® Request a feature
    url: https://github.com/Lennolium/swiftGuard/discussions/2
    about: Learn how to request a new feature.

  - name: ü§µ Get Professional Support & Customizations
    url: https://github.com/Lennolium
    about: Skip the line and get priority support directly from me.